DROP TABLE if exists product;
CREATE TABLE product(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(100),
    price INT,
    quantity SMALLINT,
    PRIMARY KEY (product_id)
);