### GET request to example server
PATCH http://localhost:8080/products/v1/update
Content-Type: application/json

{
  "updateRequests": [
    {
      "productId": 1,
      "productName": "리얼 마이바티스",
      "price": 20000,
      "quantity": 100
    }
  ]
}

###