CREATE TABLE product(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(100),
    price INT,
    quantity SMALLINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (product_id)
);

CREATE TABLE member(
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(20) UNIQUE,
    password VARCHAR(100),
    email VARCHAR(50) UNIQUE,
    role ENUM('UNVERIFIED', 'BUYER', 'SELLER', 'ADMIN'),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    left_at TIMESTAMP,
    PRIMARY KEY (member_id)
);