CREATE TABLE product(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(100),
    price INT,
    quantity SMALLINT,
PRIMARY KEY (product_id)
);

CREATE TABLE member(
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT,
    username VARCHAR(50),
    passowrd VARCHAR(100),
    email VARCHAR(60),
    role ENUM('ROLE_BUYER', 'ROLE_SELLER', 'ROLE_ADMIN')
)